-- -- Custom SQL migration file, put your code below! --
-- INSERT INTO public.tags (id,name,slug) VALUES
-- 	 (1,'Hand','hand'),
-- 	 (3,'Traditional','traditional'),
-- 	 (4,'Modern','modern'),
-- 	 (5,'Arabic','arabic'),
-- 	 (6,'Bridal','bridal'),
-- 	 (7,'Minimal','minimal'),
-- 	 (8,'Foot','foot');
